# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygram', '0007_auto_20190322_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.NullBooleanField(default=False),
        ),
    ]
