# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygram', '0012_auto_20190326_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likess',
            field=models.IntegerField(null=True),
        ),
    ]
